"""Versioned project document models."""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from datetime import datetime
from enum import Enum
from uuid import uuid4

from app.agents.schemas import utc_now
from app.core.errors import ValidationAppError


class DocumentType(str, Enum):
    """Document types generated by CastorOps."""

    REQUIREMENTS = "requirements"
    BASIC_DESIGN = "basic_design"
    API_DESIGN = "api_design"
    DATA_DESIGN = "data_design"
    OPS_DESIGN = "ops_design"
    SECURITY_DESIGN = "security_design"
    ADR = "adr"
    TASKS = "tasks"


@dataclass(frozen=True)
class Document:
    """One immutable document version."""

    id: str
    project_id: str
    doc_type: DocumentType
    version: int
    content_md: str
    generated_by: str
    prompt_hash: str
    created_at: datetime = field(default_factory=utc_now)
    references: tuple[str, ...] = field(default_factory=tuple)

    @classmethod
    def create(
        cls,
        *,
        project_id: str,
        doc_type: DocumentType,
        version: int,
        content_md: str,
        generated_by: str,
        prompt_hash: str,
        references: tuple[str, ...] = (),
    ) -> "Document":
        validate_document_input(
            project_id=project_id,
            version=version,
            content_md=content_md,
            generated_by=generated_by,
            prompt_hash=prompt_hash,
        )
        return cls(
            id=str(uuid4()),
            project_id=project_id,
            doc_type=doc_type,
            version=version,
            content_md=content_md.strip(),
            generated_by=generated_by.strip(),
            prompt_hash=prompt_hash.strip(),
            references=tuple(reference.strip() for reference in references if reference.strip()),
        )


def validate_document_input(
    *,
    project_id: str,
    version: int,
    content_md: str,
    generated_by: str,
    prompt_hash: str,
) -> None:
    if not project_id.strip():
        raise ValidationAppError("project_id must not be empty")
    if version <= 0:
        raise ValidationAppError("document version must be positive")
    if not content_md.strip():
        raise ValidationAppError("document content must not be empty")
    if len(content_md) > 500_000:
        raise ValidationAppError("document content must be 500000 characters or fewer")
    if not generated_by.strip():
        raise ValidationAppError("generated_by must not be empty")
    if not prompt_hash.strip():
        raise ValidationAppError("prompt_hash must not be empty")
